name: Test Secret Workflow

on: push

jobs:
  test-secret:
    runs-on: ubuntu-latest  # Running on the latest Ubuntu runner

    steps:
      - name: Set up secret in environment variable
        env:
          SECRET: ${{ secrets.MY_SECRET }}  # Reference the secret here
        run: |
          echo "This is my secret: $SECRET"  # GitHub should mask the secret as ***
