name: Upload and Download Artifact

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "Hello, world!" > hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-file  # Name of the artifact
          path: hello.txt   # Path of the file to be uploaded

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact  # This job depends on the successful completion of the upload-artifact job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hello-file  # The name of the artifact you want to download
      - name: Print artifact content
        run: cat hello.txt  # Print the content of the downloaded file
